services:
  postgresql:
    image: postgres:13.3
    container_name: postgres-container
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb

volumes:
  appvolume: {}